#!/usr/bin/env bash
# Regenerates documentaion and adds it to the commit
#
echo
echo "Regenerating Documentation..."
vendor/bin/apigen -q generate
echo "Regeneration complete!"
echo "Adding updated docs to commit"
git add docs
git add -u docs
echo "All done!"
