#!/usr/bin/env bash
# Regenerates documentation and adds it to the commit
#
echo "-- pre-commit script: Generate documentation --"
APIGEN='vendor/bin/apigen'
if ! [[ -f $APIGEN && -x $APIGEN ]]
then
    echo "Cannot find APIGen in vendor folder. Have you run 'composer install'?"
    exit 1
fi

echo "Regenerating Documentation..."
$APIGEN -q generate
echo "Regeneration complete!"
echo "Adding updated docs to commit"
git add docs
git add -u docs
echo "-- pre-commit script: All done! --"
